[project]
name = "data-cleaner"
version = "0.1.0"
description = "A Streamlit app for the Growth Mindset Challenge"
readme = "README.md"
requires-python = ">=3.11"
dependencies = []

[tool.poetry]
package-mode = false

